- package/docs/filters/1. array.md
- package/docs/filters/4. object.md
- package/rig/filters/array.js
- package/rig/filters/number.js
- package/rig/filters/object.js
- package/rig/filters/string.js
Adds fourth set of core filters that are provided by the Prototype Rig by default. These focus on some common transformations for objects and arrays.
* `formatList`: Convert array to a list formatted as a sentence. [Review documentation](https://govuk-protot-core-filte-r9mwbb.herokuapp.com/docs/filters/array#formatlist)
* `rejectFromArray`: Reject items in an array that have a key with a given value. [Review documentation](https://govuk-protot-core-filte-r9mwbb.herokuapp.com/docs/filters/array#rejectfromarray)
* `selectFromArray`: Select items in an array that have a key with a given value. [Review documentation](https://govuk-protot-core-filte-r9mwbb.herokuapp.com/docs/filters/array#selectfromarray)
* `objectToArray`: Transform object to an array, using key name as value for id. [Review …
> Add fourth set of core filters

- app/views/index.njk
Having a more distinctive home page is a good indicator this is a prototype, and can be a generic place to put related project links (like design history, GitHub, etc). It can also be a good way to link through to different variants if you have a prototype that has multiple entry points.
> Update prototype homepage

- app.json
- package.json
- package/lib/config.js
- package/lib/server.js
Partly fixes #25, and in service of #12.
As the prototype components get hidden away in a package, so there is a need for certain aspects to be configurable. This PR adds the ability to explicitly configure the `serviceName` (rather than rely on `app.json` whose purpose is the configuration of Heroku applications) and a `templateExtension`. This is set to `njk`, but the default if no value is given is `html`. A subsequent PR can change the example page layouts to use `.html`.
> Add package configuration options

- package/lib/config.js
- package/lib/environment.js
- package/lib/middleware/authentication.js
- package/lib/server.js
Another PR in support of #12.
Placing user config in `app.json`, which is intended for Heroku application deployment, isn’t the right approach. It has it’s own schema, which we’d need to break if we were to add custom values. It also shouldn’t be a requirement for setting up a prototype rig. (This is why in #26 we moved prototype config into `package.json` – although Cosmic Config allows config to be in any number of conventional locations).
This PR refactors how we load in config. Configuration is now managed in `lib/config.js`. In here, we provide a set of defaults (5 of which can be overridden with environment variables), and merge this with any user configuration values.
The order of priority should be:
1. Value in environment variable (if applicable)
2. Value in user configuration …
> Refactor config

- package/lib/middleware/auto-store-data.js
- package/lib/nunjucks.js
- package/lib/server.js
Another PR in support of #12.
Using relative paths isn’t a reliable method of resolving paths to files in the `./app` directory. This removes relative paths (i.e. `../../app/`) and uses `process.cwd()` instead.
> Remove relative paths in package files

- packages/govuk-prototype-rig/lib/nunjucks.js
Before this change, the global functions defined in the prototype folder weren't being registered correctly.
> Fix the loading of globals in 'app/globals.js'

- app/views/examples/autocomplete.html
- app/views/examples/question.html
- app/views/examples/validation-errors.html
- app/views/examples/validation-examples.html
- app/views/examples/wizard/england.html
- app/views/examples/wizard/name.html
- app/views/examples/wizard/nationality.html
- app/views/examples/wizard/where-do-you-live.html
- packages/govuk-prototype-components/lib/decorate.js
- packages/govuk-prototype-components/package.json
- packages/govuk-prototype-components/x-govuk/components/autocomplete/template.njk
- packages/govuk-prototype-components/x-govuk/components/decorated/checkboxes/macro.njk
- packages/govuk-prototype-components/x-govuk/components/decorated/date-input/macro.njk
- packages/govuk-prototype-components/x-govuk/components/decorated/file-upload/macro.njk
- packages/govuk-prototype-components/x-govuk/components/decorated/input/macro.njk
- packages/govuk-prototype-components/x-govuk/components/decorated/radios/macro.njk
- packages/govuk-prototype-components/x-govuk/components/decorated/select/macro.njk
- packages/govuk-prototype-components/x-govuk/components/decorated/textarea/macro.njk
- packages/govuk-prototype-rig/docs/using-data/1. form-components.md
- packages/govuk-prototype-rig/docs/using-data/2. wizard.md
- packages/govuk-prototype-rig/lib/globals/checked.js
- packages/govuk-prototype-rig/lib/globals/helper.js
- packages/govuk-prototype-rig/lib/globals/index.js
- packages/govuk-prototype-rig/views/feature-flags.njk
- packages/govuk-prototype-rig/views/template.njk
Add a `decorate: 'name'` parameter to any of the GOVUK form components to automatically decorate them, without having to use the more fiddly function syntax.
```
{{ govukInput(decorate({
label: {
text: "First name"
}
}, 'first-name')) }}
```
```
{{ govukInput({
decorate: 'first-name',
label: {
text: "First name"
}
}) }}
```
To do:
> Allow form controls to be decorated with a parameter

- package-lock.json
- packages/govuk-prototype-components/package.json
`decorate` uses lodash and decorate is now part of this component
> Add missing lodash dependency

- app/views/examples/validation-error.html
- packages/govuk-prototype-rig/lib/form-validation.js
- packages/govuk-prototype-rig/views/template.njk
- Use GOVUKFrontend.ErrorSummary to focus the error summary component
- Insert the error summary just inside the main element
- Include an example of validation where the h1 is within the form
`.focus()` isn't enough, we need to use the ErrorSummary js to also append a tabindex attribute beforehand.
See: https://github.com/alphagov/govuk-frontend/blob/974482f96dfb1c2cdf732e70272f233190ef9839/src/govuk/components/error-summary/error-summary.js
| Before | After |
|--|--|
| ![Screenshot 2022-03-03 at 16 33 40](https://user-images.githubusercontent.com/319055/156615104-df0cf20b-aae3-4951-a0d3-aadd287d3628.png) | ![Screenshot 2022-03-03 at 17 09 04](https://user-images.githubusercontent.com/319055/156615196-2c2e959b-4849-41d1-994e-4120c9c38607.png) |
> Fixes to validation

- packages/govuk-prototype-rig/lib/config.js
Users can be inputting sensitive data into prototypes, this should always be over https.
> Default to using HTTPS

- packages/govuk-prototype-rig/lib/form-validation.js
Without this return, there can be a flash of DOM changes before the next page loads – this is jarring. If we’re submitting the form we don't need to manipulate the DOM.
https://user-images.githubusercontent.com/319055/157657374-f42b1f14-6a23-4376-a7aa-52e8714503d3.mov
https://user-images.githubusercontent.com/319055/157657566-9e752157-fa48-4edc-9251-23fbbce849ee.mov
> Add an early return if there are no errors

- app/views/examples/validation-examples.html
- docs/about.md
- docs/using-data/feature-flags.md
- docs/using-data/form-components.md
- docs/using-data/form-validation.md
- docs/using-data/wizard.md
- lib/form-validation.js
Definitely be good to get a second pair of eyes on this… there’s only so many times you can write validate, validator and validation in the same document without considering your life choices.
Also fixes form validation JavaScript: `window.GOVUKFrontend` no longer exists.
Fixes #13.
> Add documentation for form validation feature

- docs/filters/number.md
- lib/filters/number.js
Convert a number into an ordinal numeral that follows [the GOV.UK style](https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#ordinal-numbers).
Input
```njk
{{ 4 | ordinal }}
{{ 22 | ordinal }}
```
Output
```html
fourth
22nd
```
> Add ordinal filter

- docs/filters/string.md
- lib/filters/string.js
Get the plural form for an item for a given number of items.
```njk
{{ 1 | pluralise("mouse") }}
{{ 2 | pluralise("house") }}
{{ 2 | pluralise("house", { number: false }) }}
{{ 2 | pluralise("mouse", { plural: "mice" }) }}
{{ 2 | pluralise("mouse", { plural: "mice", number: false }) }}
```
Output
```html
1 mouse
2 houses
houses
10 mice
mice
```
> Add pluralise filter

- docs/about.md
- lib/server.js
- lib/views/500.njk
In addition to the error message, now also shows the name of the error and the stack trace:
> Enhanced error page

- docs/options.md
- lib/views/404.njk
- lib/views/500.njk
- lib/views/clear-session-data.njk
- lib/views/feature-flags.njk
- lib/views/no-password-set.njk
- lib/views/password.njk
Adds two choices:
1. defaultLayout
2. errorLayout
This is a non-breaking change as it will default to the existing template if no other one is given.
This will let the rig’s pages use things like a common footer, or other customisations.
Example usage:
```
"prototype": {
"serviceName": "Find a lost teacher reference number (TRN)",
"defaultLayout": "layouts/default.html"
}
```
Note the custom layout and different footer now used by the clear session page:
> Allow rig views to extend a prototype layout

- lib/views/template.njk
- package-lock.json
- package.json
Add support for GOV.UK Frontend v4.2.0. Requires increasing minimum version of the `govuk-frontend` dependency and including the `govukPagination` macro in the base template.
> Add support for GOV.UK Frontend v4.2.0

- lib/middleware/auto-store-data.js
- lib/nunjucks.js
- lib/server.js
Going by similar issues as #161 reported on other projects, it appears that [`pathToFileURL`](https://nodejs.org/api/url.html#urlpathtofileurlpath) should be used when passing paths to `import()`. This ensures the `file:` protocol is used, and not local file paths such as those used by Windows that may begin with something like `c:`.
🤞 this fixes this compatibility issue on Windows.
> Ensure file paths used for dynamic imports. fixes #161

- lib/globals/index.js
- lib/nunjucks.js
- lib/views/template.njk
- package-lock.json
- package.json
Use the new [`govuk-decorated-components`](https://github.com/x-govuk/govuk-decorated-components) package.
@fofr If you approve this PR, I’ll release the above as a package on npm and update this PR to point to the published package.
> Use new decorated components module

- package.json
Without this, Heroku installs the latest possible Node, which is currently 19. This fails to build at the moment.
Fixes #183.
> Specify a max node version
